#!/usr/bin/env python3
"""Rebuild APPENDIX_EXECUTION_MAP.md from live spec files."""
from pathlib import Path
import re
import json
from collections import OrderedDict

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "spec"
PLAN = ROOT / "recon/plans"
EXEC_MAP = PLAN / "APPENDIX_EXECUTION_MAP.md"

required = ["M0", "M1", "M2", "M3", "M4", "M4.5", "M5", "M6", "M6.5", "M7", "M8", "M9", "M10", "M11", "M12", "M13"]
milestones = OrderedDict()

for ms in required:
    text = (SPEC / f"{ms}.md").read_text(encoding="utf-8", errors="ignore")
    ids = sorted(set(re.findall(rf"{ms}-EXT-(\d+)", text)), key=int)
    max_id = ids[-1] if ids else 0
    block_count = len(ids)
    
    # Extract titles for first few blocks
    samples = []
    for block_num in ids[:3]:
        block_id = f"{ms}-EXT-{block_num}"
        anchor = f"#### [{block_id}]"
        idx = text.find(anchor)
        if idx == -1:
            anchor_lower = anchor.lower()
            idx = text.lower().find(anchor_lower)
        if idx != -1:
            snippet = text[idx:idx + 600]
            m = re.search(r"^####\s*\[[^\]]+\]\s*(.*)$", snippet, re.MULTILINE)
            if m:
                title = m.group(1).strip()
                if title:
                    samples.append(f"{block_id}: {title}")
                    continue
        samples.append(f"{block_id}: Systems Touched")
    
    milestones[ms] = {
        "count": block_count,
        "max_id": max_id,
        "samples": samples,
    }

total = sum(m["count"] for m in milestones.values())

lines = [
    "# Appendix Execution Map",
    "> Rebuilt from live spec/*.md files.",
    f"> Block count: {total} across {len(milestones)} milestones",
    "> Rule: all IDs verified against disk; do not hardcode without grep check",
    "",
    "## 1. Milestone block inventory",
    "",
    "| Milestone | Blocks | Max EXT | Sample blocks |",
    "|-----------|--------|---------|---------------|",
]

for ms, data in milestones.items():
    samples_str = "; ".join(data["samples"][:3])
    lines.append(f"| {ms} | {data['count']} | {data['max_id']} | {samples_str} |")

lines += [
    "",
    f"**Total blocks**: {total}",
    "",
    "## 2. Dependency order",
    "",
    "Execute blocks in milestone order; within each milestone, EXT-ID order is dependency order.",
    "Cross-milestone deps are declared in each block's `depends-on` metadata.",
    "",
    "Verified execution order:",
]

for ms in required:
    lines.append(f"- {ms}: {milestones[ms]['count']} blocks")

lines += [
    "",
    "## 3. Acceptance tests",
    "",
    "Per batch:",
    "- Code compiles under MSVC 14.44.35207 with Ninja",
    "- Unit test added in tests/unit/ with pass/fail assertion",
    "- If block has reference implementation, compile and run the snippet or its unit test",
    "- If block has no reference implementation, acceptance test is explicit math/spec review with sign-off",
    "",
    "Per repo:",
    "- git status --short returns only planned changes for the batch",
    "- 20/20 unit tests still pass",
    "- headless smoke test still exits 0",
    "",
    "## 4. ID collision check",
    "",
    "Before merging any block, grep spec/ and APPENDICES.md for the exact ID.",
    "If a collision is found, treat the ID as provisional and rename before commit.",
    "",
    "## 5. Source of truth",
    "",
    "- Block IDs: parsed from spec/<ms>.md via regex `{ms}-EXT-(\d+)`",
    "- True ceilings: highest EXT number found in each milestone file",
    "- Counts: unique EXT IDs per milestone",
    "- This file is auto-generated by `scripts/rebuild_execution_map.py`",
]

EXEC_MAP.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Wrote: {EXEC_MAP}")
print(f"Total blocks: {total}")
print(f"Milestones: {len(milestones)}")
