add_subdirectory(ai)
add_subdirectory(audio)
add_subdirectory(combat)
add_subdirectory(core)
add_subdirectory(debug)
add_subdirectory(ecs)
add_subdirectory(events)
add_subdirectory(modding)
add_subdirectory(net)
add_subdirectory(physics)
add_subdirectory(render)
add_subdirectory(save)
add_subdirectory(slm)
add_subdirectory(survival)
add_subdirectory(ui)
add_subdirectory(vehicle)
add_subdirectory(world)
